using System;
using System.Collections.Generic;
using System.Text;

namespace Nop.Web.Infrastructure
{
    public static class StopWordProvider
    {
        /// <summary>
        /// Words we want to remove.
        /// </summary>
        private static readonly Dictionary<string, bool> Stops = new Dictionary<string, bool>
        {
            {"ad", true},
            {"al", true},
            {"allo", true},
            {"ai", true},
            {"agli", true},
            {"all", true},
            {"agl", true},
            {"alla", true},
            {"alle", true},
            {"con", true},
            {"col", true},
            {"coi", true},
            {"da", true},
            {"dal", true},
            {"dallo", true},
            {"dai", true},
            {"dagli", true},
            {"dall", true},
            {"dagl", true},
            {"dalla", true},
            {"dalle", true},
            {"di", true},
            {"del", true},
            {"dello", true},
            {"dei", true},
            {"degli", true},
            {"dell", true},
            {"degl", true},
            {"della", true},
            {"delle", true},
            {"in", true},
            {"nel", true},
            {"nello", true},
            {"nei", true},
            {"negli", true},
            {"nell", true},
            {"negl", true},
            {"nella", true},
            {"nelle", true},
            {"su", true},
            {"sul", true},
            {"sullo", true},
            {"sui", true},
            {"sugli", true},
            {"sull", true},
            {"sugl", true},
            {"sulla", true},
            {"sulle", true},
            {"per", true},
            {"tra", true},
            {"contro", true},
            {"io", true},
            {"tu", true},
            {"lui", true},
            {"lei", true},
            {"noi", true},
            {"voi", true},
            {"loro", true},
            {"mio", true},
            {"mia", true},
            {"miei", true},
            {"mie", true},
            {"tuo", true},
            {"tua", true},
            {"tuoi", true},
            {"tue", true},
            {"suo", true},
            {"sua", true},
            {"suoi", true},
            {"sue", true},
            {"nostro", true},
            {"nostra", true},
            {"nostri", true},
            {"nostre", true},
            {"vostro", true},
            {"vostra", true},
            {"vostri", true},
            {"vostre", true},
            {"mi", true},
            {"ti", true},
            {"ci", true},
            {"vi", true},
            {"lo", true},
            {"la", true},
            {"li", true},
            {"le", true},
            {"gli", true},
            {"ne", true},
            {"il", true},
            {"un", true},
            {"uno", true},
            {"una", true},
            {"ma", true},
            {"ed", true},
            {"se", true},
            {"perché", true},
            {"anche", true},
            {"come", true},
            {"dov", true},
            {"dove", true},
            {"che", true},
            {"chi", true},
            {"cui", true},
            {"non", true},
            {"più", true},
            {"quale", true},
            {"quanto", true},
            {"quanti", true},
            {"quanta", true},
            {"quante", true},
            {"quello", true},
            {"quelli", true},
            {"quella", true},
            {"quelle", true},
            {"questo", true},
            {"questi", true},
            {"questa", true},
            {"queste", true},
            {"si", true},
            {"tutto", true},
            {"tutti", true},
            {"a", true},
            {"c", true},
            {"e", true},
            {"i", true},
            {"l", true},
            {"o", true},
            {"ho", true},
            {"hai", true},
            {"ha", true},
            {"abbiamo", true},
            {"avete", true},
            {"hanno", true},
            {"abbia", true},
            {"abbiate", true},
            {"abbiano", true},
            {"avrò", true},
            {"avrai", true},
            {"avrà", true},
            {"avremo", true},
            {"avrete", true},
            {"avranno", true},
            {"avrei", true},
            {"avresti", true},
            {"avrebbe", true},
            {"avremmo", true},
            {"avreste", true},
            {"avrebbero", true},
            {"avevo", true},
            {"avevi", true},
            {"aveva", true},
            {"avevamo", true},
            {"avevate", true},
            {"avevano", true},
            {"ebbi", true},
            {"avesti", true},
            {"ebbe", true},
            {"avemmo", true},
            {"aveste", true},
            {"ebbero", true},
            {"avessi", true},
            {"avesse", true},
            {"avessimo", true},
            {"avessero", true},
            {"avendo", true},
            {"avuto", true},
            {"avuta", true},
            {"avuti", true},
            {"avute", true},
            {"sono", true},
            {"sei", true},
            {"è", true},
            {"siamo", true},
            {"siete", true},
            {"sia", true},
            {"siate", true},
            {"siano", true},
            {"sarò", true},
            {"sarai", true},
            {"sarà", true},
            {"saremo", true},
            {"sarete", true},
            {"saranno", true},
            {"sarei", true},
            {"saresti", true},
            {"sarebbe", true},
            {"saremmo", true},
            {"sareste", true},
            {"sarebbero", true},
            {"ero", true},
            {"eri", true},
            {"era", true},
            {"eravamo", true},
            {"eravate", true},
            {"erano", true},
            {"fui", true},
            {"fosti", true},
            {"fu", true},
            {"fummo", true},
            {"foste", true},
            {"furono", true},
            {"fossi", true},
            {"fosse", true},
            {"fossimo", true},
            {"fossero", true},
            {"essendo", true},
            {"faccio", true},
            {"fai", true},
            {"facciamo", true},
            {"fanno", true},
            {"faccia", true},
            {"facciate", true},
            {"facciano", true},
            {"farò", true},
            {"farai", true},
            {"farà", true},
            {"faremo", true},
            {"farete", true},
            {"faranno", true},
            {"farei", true},
            {"faresti", true},
            {"farebbe", true},
            {"faremmo", true},
            {"fareste", true},
            {"farebbero", true},
            {"facevo", true},
            {"facevi", true},
            {"faceva", true},
            {"facevamo", true},
            {"facevate", true},
            {"facevano", true},
            {"feci", true},
            {"facesti", true},
            {"fece", true},
            {"facemmo", true},
            {"faceste", true},
            {"fecero", true},
            {"facessi", true},
            {"facesse", true},
            {"facessimo", true},
            {"facessero", true},
            {"facendo", true},
            {"sto", true},
            {"stai", true},
            {"sta", true},
            {"stiamo", true},
            {"stanno", true},
            {"stia", true},
            {"stiate", true},
            {"stiano", true},
            {"starò", true},
            {"starai", true},
            {"starà", true},
            {"staremo", true},
            {"starete", true},
            {"staranno", true},
            {"starei", true},
            {"staresti", true},
            {"starebbe", true},
            {"staremmo", true},
            {"stareste", true},
            {"starebbero", true},
            {"stavo", true},
            {"stavi", true},
            {"stava", true},
            {"stavamo", true},
            {"stavate", true},
            {"stavano", true},
            {"stetti", true},
            {"stesti", true},
            {"stette", true},
            {"stemmo", true},
            {"steste", true},
            {"stettero", true},
            {"stessi", true},
            {"stesse", true},
            {"stessimo", true},
            {"stessero", true},
            {"stando", true}
        };

        /// <summary>
        /// Chars that separate words.
        /// </summary>
        private static readonly char[] Delimiters = new char[]
        {
        ' ',
        ',',
        ';',
        '.'
        };

        /// <summary>
        /// Remove stopwords from string.
        /// </summary>
        public static string RemoveStopwords(string input)
        {
            // 1
            // Split parameter into words
            var words = input.Split(Delimiters,
                StringSplitOptions.RemoveEmptyEntries);
            // 2
            // Allocate new dictionary to store found words
            var found = new Dictionary<string, bool>();
            // 3
            // Store results in this StringBuilder
            StringBuilder builder = new StringBuilder();
            // 4
            // Loop through all words
            foreach (string currentWord in words)
            {
                // 5
                // Convert to lowercase
                string lowerWord = currentWord.ToLower();
                // 6
                // If this is a usable word, add it
                if (!Stops.ContainsKey(lowerWord) &&
                    !found.ContainsKey(lowerWord))
                {
                    builder.Append(currentWord).Append(' ');
                    found.Add(lowerWord, true);
                }
            }
            // 7
            // Return string with words removed
            return builder.ToString().Trim();
        }
    }
}
